source $HOME/.config/rc/specific/zshInit.sh
source $HOME/.secrets
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
export PATH="$HOME/.cargo/bin:$PATH"
alias notebook="uvr --with euporie euporie-notebook"
