hl.curve("smoothEaseOut",  { type = "bezier", points = { {0.16, 1},    {0.3, 1}      } })
hl.curve("easeOutExpo",    { type = "bezier", points = { {0.19, 1},    {0.22, 1}     } })
hl.curve("easeInOutQuad",  { type = "bezier", points = { {0.45, 0.05}, {0.55, 0.95}  } })
hl.curve("easeOutQuad",    { type = "bezier", points = { {0.25, 0.46}, {0.45, 0.94}  } })
hl.curve("easeInQuad",     { type = "bezier", points = { {0.55, 0.085},{0.68, 0.53}  } })
hl.curve("snappy",         { type = "bezier", points = { {0.1, 0.8},   {0.2, 1}      } })
hl.curve("bounce",         { type = "bezier", points = { {0.34, 1.56}, {0.64, 1}     } })
hl.curve("elasticInOut",   { type = "bezier", points = { {0.68, -0.55},{0.265, 1.55} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}        } })

hl.animation({ leaf = "global",        enabled = true, speed = 7,   bezier = "smoothEaseOut" })
hl.animation({ leaf = "border",        enabled = true, speed = 3.5, bezier = "snappy" })
hl.animation({ leaf = "windows",       enabled = true, speed = 5,   bezier = "easeOutExpo" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 5,   bezier = "easeOutExpo",   style = "popin 80%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 2,   bezier = "easeOutQuad",   style = "popin 80%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 2,   bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.5, bezier = "easeOutQuad" })
hl.animation({ leaf = "fade",          enabled = true, speed = 2.5, bezier = "easeInOutQuad" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.5, bezier = "smoothEaseOut" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 3.5, bezier = "smoothEaseOut", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 2,   bezier = "easeOutQuad",   style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 2,   bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.5, bezier = "easeOutQuad" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 2.5, bezier = "easeInOutQuad", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 2,   bezier = "easeOutExpo",   style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 2,   bezier = "easeOutQuad",   style = "slide" })
