
windowrule {
    name = xwayland-current-monitor
    match:xwayland = 1
    monitor=current
}

windowrule {
    name = float
    match:class = ^(spotify|pcmanfm|R.float|protonvpn-app|xdg-desktop-portal-gtk|org.pulseaudio.pavucontrol|blueman-manager)$
    float = true
    center = true
    size = 800 500

}
